"""stas fix

Revision ID: 0b8aa0974043
Revises: ba8f8144e5f1
Create Date: 2022-06-10 22:32:46.947726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8aa0974043'
down_revision = 'ba8f8144e5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
