"""fix backref

Revision ID: 0d4ce4f12edd
Revises: 1f14ca00e63c
Create Date: 2022-06-10 22:12:29.571176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4ce4f12edd'
down_revision = '1f14ca00e63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
