"""fixing links

Revision ID: 1f14ca00e63c
Revises: abc55a14b1c5
Create Date: 2022-06-10 20:55:22.203882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f14ca00e63c'
down_revision = 'abc55a14b1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
