"""add coalition

Revision ID: 24ea9bcf3bf5
Revises: 13b66bfb15fa
Create Date: 2022-06-25 15:05:41.867523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ea9bcf3bf5'
down_revision = '13b66bfb15fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('coalition_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parties', 'parties', ['coalition_id'], ['id'])
    op.create_unique_constraint(None, 'statsdata', ['candidate_id', 'batchname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statsdata', type_='unique')
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_column('parties', 'coalition_id')
    # ### end Alembic commands ###
