"""add stats tables,add candi columns

Revision ID: 27ef40c8637b
Revises: 3530ca62396d
Create Date: 2022-06-10 20:44:06.460387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ef40c8637b'
down_revision = '3530ca62396d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statsources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statsources_code'), 'statsources', ['code'], unique=True)
    op.create_index(op.f('ix_statsources_name'), 'statsources', ['name'], unique=True)
    op.create_table('statsbatch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batchname', sa.String(), nullable=True),
    sa.Column('batchdate', sa.Date(), nullable=True),
    sa.Column('statssource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['statssource_id'], ['statsources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statsbatch_batchname'), 'statsbatch', ['batchname'], unique=True)
    op.create_table('statsdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('statsbatch_id', sa.Integer(), nullable=True),
    sa.Column('votes', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['statsbatch_id'], ['statsbatch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidates', sa.Column('won', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('county_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('deputy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'counties', ['county_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'candidates', ['deputy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'deputy_id')
    op.drop_column('candidates', 'county_id')
    op.drop_column('candidates', 'won')
    op.drop_table('statsdata')
    op.drop_index(op.f('ix_statsbatch_batchname'), table_name='statsbatch')
    op.drop_table('statsbatch')
    op.drop_index(op.f('ix_statsources_name'), table_name='statsources')
    op.drop_index(op.f('ix_statsources_code'), table_name='statsources')
    op.drop_table('statsources')
    # ### end Alembic commands ###
