"""removechairman

Revision ID: 2cdfbee0d0c0
Revises: d30d7fc3f829
Create Date: 2022-05-22 18:28:15.967354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdfbee0d0c0'
down_revision = 'd30d7fc3f829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parties_chairman_id_fkey', 'parties', type_='foreignkey')
    op.drop_column('parties', 'chairman_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('chairman_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parties_chairman_id_fkey', 'parties', 'candidates', ['chairman_id'], ['id'])
    # ### end Alembic commands ###
