"""addslogan, add county

Revision ID: 3530ca62396d
Revises: 8ed39d414589
Create Date: 2022-06-01 17:50:50.347607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3530ca62396d'
down_revision = '8ed39d414589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counties_code'), 'counties', ['code'], unique=True)
    op.create_index(op.f('ix_counties_name'), 'counties', ['name'], unique=True)
    op.add_column('candidates', sa.Column('slogan', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'color')
    op.drop_column('candidates', 'slogan')
    op.drop_index(op.f('ix_counties_name'), table_name='counties')
    op.drop_index(op.f('ix_counties_code'), table_name='counties')
    op.drop_table('counties')
    # ### end Alembic commands ###
