"""postaladdress

Revision ID: 8ed39d414589
Revises: 2cdfbee0d0c0
Create Date: 2022-05-22 21:50:50.921176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed39d414589'
down_revision = '2cdfbee0d0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('symbol', sa.String(), nullable=True))
    op.add_column('parties', sa.Column('colors', sa.String(), nullable=True))
    op.add_column('parties', sa.Column('postaladdress', sa.String(), nullable=True))
    op.add_column('parties', sa.Column('officelocation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'officelocation')
    op.drop_column('parties', 'postaladdress')
    op.drop_column('parties', 'colors')
    op.drop_column('parties', 'symbol')
    # ### end Alembic commands ###
