"""fix county link

Revision ID: 9eae95a86849
Revises: 0b8aa0974043
Create Date: 2022-06-10 22:35:27.498620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eae95a86849'
down_revision = '0b8aa0974043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
