"""attach county to candidate

Revision ID: abc55a14b1c5
Revises: 27ef40c8637b
Create Date: 2022-06-10 20:47:26.149078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc55a14b1c5'
down_revision = '27ef40c8637b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
