"""addslogan

Revision ID: ad22ddf35f06
Revises: e1e5bec3ca7f
Create Date: 2022-05-22 17:01:16.847938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad22ddf35f06'
down_revision = 'e1e5bec3ca7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('slogan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'slogan')
    # ### end Alembic commands ###
