"""change datetime for settings

Revision ID: ad58066e7022
Revises: c338c69e33e2
Create Date: 2022-06-14 18:33:08.763105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad58066e7022'
down_revision = 'c338c69e33e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
