"""allow foreign nulls

Revision ID: ad687a2090c1
Revises: b46b1ca847a0
Create Date: 2022-06-12 13:22:02.428450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad687a2090c1'
down_revision = 'b46b1ca847a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
