"""added settings table

Revision ID: b46b1ca847a0
Revises: 9eae95a86849
Create Date: 2022-06-10 22:52:35.609515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46b1ca847a0'
down_revision = '9eae95a86849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defaultsdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('totalvotes', sa.DECIMAL(), nullable=True),
    sa.Column('electiondate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defaultsdata')
    # ### end Alembic commands ###
