"""attach county to candidate

Revision ID: ba8f8144e5f1
Revises: 0d4ce4f12edd
Create Date: 2022-06-10 22:30:07.189397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8f8144e5f1'
down_revision = '0d4ce4f12edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
