"""remove unique from batchname

Revision ID: c0db4aa07eb0
Revises: 24ea9bcf3bf5
Create Date: 2022-06-25 15:06:32.917428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0db4aa07eb0'
down_revision = '24ea9bcf3bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_statsdata_batchname', table_name='statsdata')
    op.create_index(op.f('ix_statsdata_batchname'), 'statsdata', ['batchname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statsdata_batchname'), table_name='statsdata')
    op.create_index('ix_statsdata_batchname', 'statsdata', ['batchname'], unique=False)
    # ### end Alembic commands ###
