"""update link to candidate

Revision ID: c338c69e33e2
Revises: ad687a2090c1
Create Date: 2022-06-13 18:24:22.512299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c338c69e33e2'
down_revision = 'ad687a2090c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
