"""morecolumns

Revision ID: d30d7fc3f829
Revises: 1832cc338ac7
Create Date: 2022-05-22 17:45:34.674050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30d7fc3f829'
down_revision = '1832cc338ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('party_code', sa.String(), nullable=True))
    op.add_column('parties', sa.Column('chairman_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parties_party_code'), 'parties', ['party_code'], unique=True)
    op.create_foreign_key(None, 'parties', 'candidates', ['chairman_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_index(op.f('ix_parties_party_code'), table_name='parties')
    op.drop_column('parties', 'chairman_id')
    op.drop_column('parties', 'party_code')
    # ### end Alembic commands ###
