"""change statstables

Revision ID: d9282ea5a5b3
Revises: ad58066e7022
Create Date: 2022-06-14 18:36:11.767004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9282ea5a5b3'
down_revision = 'ad58066e7022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statsbatch_statssource_id_fkey', 'statsbatch', type_='foreignkey')
    op.drop_column('statsbatch', 'statssource_id')
    op.add_column('statsdata', sa.Column('batchname', sa.String(), nullable=True))
    op.add_column('statsdata', sa.Column('batchdate', sa.DateTime(), nullable=True))
    op.add_column('statsdata', sa.Column('statssource_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_statsdata_batchname'), 'statsdata', ['batchname'], unique=True)
    op.create_foreign_key(None, 'statsdata', 'statsources', ['statssource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statsdata', type_='foreignkey')
    op.drop_index(op.f('ix_statsdata_batchname'), table_name='statsdata')
    op.drop_column('statsdata', 'statssource_id')
    op.drop_column('statsdata', 'batchdate')
    op.drop_column('statsdata', 'batchname')
    op.add_column('statsbatch', sa.Column('statssource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('statsbatch_statssource_id_fkey', 'statsbatch', 'statsources', ['statssource_id'], ['id'])
    # ### end Alembic commands ###
