"""added columns

Revision ID: e1e5bec3ca7f
Revises: 65a0e46062ab
Create Date: 2022-05-22 16:05:22.345064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e5bec3ca7f'
down_revision = '65a0e46062ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('short_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_candidates_short_code'), 'candidates', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_short_code'), table_name='candidates')
    op.drop_column('candidates', 'short_code')
    # ### end Alembic commands ###
