"""test col

Revision ID: ece091928d9b
Revises: 
Create Date: 2022-05-14 18:41:33.850003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece091928d9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'name1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('name1', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
